.catalog:
  name: "GitLab Runner"
  version: 0.0.1
  description: |
    See the readme of the original repo for more details.
  questions:
    - variable: "RUNNER_IMAGE_VERSION"
      label: "Image Version"
      description: "Dockerhub image version of gitlab runner"
      required: true
      default: "alpine-v9.2.0-rc.2"
      type: "string"
