version: '2'

volumes:
  redis-data:
    driver: ${REDIS_DATA_STORAGE_DRIVER}
  postgresql-data:
    driver: ${POSTGRES_DATA_STORAGE_DRIVER}
  gitlab-data:
    driver: ${GITLAB_DATA_STORAGE_DRIVER}

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - redis-data:/var/lib/redis
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: type=gitlab,role=redis
      io.rancher.container.hostname_override: container_name

  postgres:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - postgresql-data:/var/lib/postgresql
    environment:
      DB_USER: gitlab
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: gitlabhq_production
      DB_EXTENSION: pg_trgm
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: type=gitlab,role=db
      io.rancher.container.hostname_override: container_name

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.1.4
    depends_on:
    - redis
    - postgresql
    volumes:
    - gitlab-data:/home/git/data:Z
    ports:
    - "${GITLAB_SSH_PORT}:22"
    environment:
      DEBUG: ${GITLAB_DEBUG}

      DB_ADAPTER: postgresql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: gitlab
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: gitlabhq_production

      REDIS_HOST: redis
      REDIS_PORT: 6379

      TZ: ${GITLAB_TZ}
      GITLAB_TIMEZONE: ${GITLAB_APP_TZ}

      GITLAB_HTTPS: ${GITLAB_HTTPS}
      SSL_SELF_SIGNED: false

      GITLAB_HOST: ${GITLAB_HOST}
      GITLAB_PORT: ${GITLAB_PORT}
      GITLAB_SSH_PORT: ${GITLAB_SSH_PORT}
      GITLAB_SECRETS_DB_KEY_BASE: ${GITLAB_SECRETS_DB}
      GITLAB_SECRETS_SECRET_KEY_BASE: ${GITLAB_SECRETS_SECRET}
      GITLAB_SECRETS_OTP_KEY_BASE: ${GITLAB_SECRETS_OTP}

      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB_ROOT_EMAIL: ${GITLAB_ROOT_EMAIL}

      GITLAB_NOTIFY_ON_BROKEN_BUILDS: true
      GITLAB_NOTIFY_PUSHER: false

      GITLAB_SIGNUP_ENABLED: ${GITLAB_SIGNUP_ENABLED}

      GITLAB_EMAIL: ${GITLAB_EMAIL}
      GITLAB_EMAIL_DISPLAY_NAME: ${GITLAB_EMAIL_DISPLAY_NAME}
      GITLAB_EMAIL_REPLY_TO: ${GITLAB_EMAIL_REPLY_TO}
      GITLAB_EMAIL_SUBJECT_SUFFIX: ${GITLAB_EMAIL_SUBJECT_SUFFIX}

      SMTP_ENABLED: ${SMTP_ENABLED}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_STARTTLS: ${SMTP_STARTTLS}

      IMAP_ENABLED: ${IMAP_ENABLED}
      IMAP_HOST: ${IMAP_HOST}
      IMAP_PORT: ${IMAP_PORT}
      IMAP_USER: ${IMAP_USER}
      IMAP_PASS: ${IMAP_PASS}
      IMAP_SSL: ${IMAP_SSL}
      IMAP_STARTTLS: ${IMAP_STARTTLS}

      GITLAB_BACKUP_SCHEDULE: ${GITLAB_BACKUP_SCHEDULE}
      GITLAB_BACKUP_EXPIRY: ${GITLAB_BACKUP_EXPIRY}
      GITLAB_BACKUP_TIME: ${GITLAB_BACKUP_TIME}
      GITLAB_BACKUP_SKIP: ${GITLAB_BACKUP_SKIP}

      AWS_BACKUPS: ${AWS_BACKUPS}
      AWS_BACKUP_REGION: ${AWS_BACKUP_REGION}
      AWS_BACKUP_BUCKET: ${AWS_BACKUP_BUCKET}
      AWS_BACKUP_ACCESS_KEY_ID: ${AWS_BACKUP_ACCESS_KEY_ID}
      AWS_BACKUP_SECRET_ACCESS_KEY: ${AWS_BACKUP_SECRET_ACCESS_KEY}
      AWS_BACKUP_MULTIPART_CHUNK_SIZE: ${AWS_BACKUP_MULTIPART_CHUNK_SIZE}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: type=gitlab
      io.rancher.container.hostname_override: container_name
      rap.host: ${RAP_HOST}
      rap.port: 80
      rap.https_method: ${RAP_HTTPS_METHOD}
      rap.le_host: ${RAP_LE_HOST}
      rap.le_email: ${RAP_LE_EMAIL}
      rap.le_test: ${RAP_LE_TEST}
      rap.http_listen_ports: ${RAP_HTTP_EXT_PORT}
      rap.https_listen_ports: ${RAP_HTTPS_EXT_PORT}
      rap.client_max_body_size: 0
