name: Registry with Portus UI
description: |
  Secure Docker registry.  Web based administration.  Optional LDAP authentication.
version: 1.0.2
category: Applications
maintainer: Roy Tsang <roy@roytsang.com>
